[phases.setup]
nixPkgs = ["nodejs", "npm", "chromium", "procps"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm run start:prod"

[envs]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "1"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
